[Content]
Packages =
  python3
  python3-sqlalchemy
  python3-graphviz
  python3-flask
  python3-flask-sqlalchemy
  python3-wtforms
  python3-werkzeug
  python3-jwt
  python3-email-validator
  gunicorn
  ipython3

  latexmk
  texlive-latex-extra
  texlive-fonts-recommended
  texlive-luatex
  fonts-noto-core
  poppler-utils
  graphviz
  wngerman

ExtraTrees = moerderspiel:/opt/moerderspiel/moerderspiel