MAX_PLAYER_NAME_LENGTH = 32
MAX_GROUP_NAME_LENGTH = 32
MAX_CIRCLE_NAME_LENGTH = 16
MAX_CIRCLE_SET_NAME_LENGTH = 16
MAX_GAME_ID_LENGTH = 16
MAX_GAME_TITLE_LENGTH = 32
MAX_MURDER_DESCRIPTION_LENGTH = 256

MISSION_CODE_LENGTH = 6
